---
lang: de
title: "ContentPool: ACP-Manager"
---

Ein Assessment Content Package (ACP) muss vorher über einen Nutzer mit der Rolle "Application-Admin" angelegt werden. Außerdem muss mindestens einem Nutzer die Rolle "**ACP-Manager**" zugewiesen sein. Nach dem Login erhält ein ACP-Manager eine Liste aller ACP, auf die er Zugriff hat, und kann in ein ACP wechseln. Die Rolle ACP-Manager hat das Recht, für das ACP folgende Funktionen auszuführen:

# Allgemeines Datenmanagement

* Ansicht, Upload, Download und Ändern von Daten des ACP-Index
* Upload und Download von ACP-Dateien
* Snapshot erzeugen
* Snapshot wiederherstellen
* Download und Löschen ggf. der über den Nur-Lese-Zugriff vergebenen Kommentare

# Nur-Lese-Zugriff auf das ACP erteilen

Der ACP-Manager kann einen Nur-Lese-Zugriff auf das ACP erteilen. Hierfür gibt es drei Modelle:

1. **Keine Beschränkung (Public)**: Bei diesem Modell hat jede nicht autorisierte Person Zugriff. Es gibt keine zeitliche Begrenzung. Der ACP wird auf der Startseite der Webanwendung ContentPool mit dem Namen und einer Beschreibung aufgeführt, so dass Interessierte zu den Daten des ACP finden.
2. **Nutzer des ContentPool**: Ein ACP-Manager kann einem Nutzer, der vorher durch einen Application-Admin angelegt wurde, für das ACP die Rolle Nur-Lese-Zugriff geben. Nach dem Login erhält der Nutzer dann eine Liste aller ACP, auf die er Zugriff hat, und kann in diese ACP wechseln.
3. **Benutzername und Kennwort**: Ein ACP-Manager kann eine Liste erstellen oder hochladen, in der pro Zeile ein Benutzername und ein Kennwort festgelegt ist. Diese Daten autorisieren den Nur-Lese-Zugriff für das ACP. Der ACP-Manager muss den Zugriff über diese Liste zeitlich begrenzen. Es ist ein Zeitraum von maximal 3 Monaten zulässig. Ein ACP, das über diesen Weg einen Zugriff erlaubt, wird auf der Startseite der Webanwendung ContentPool mit dem Namen und einer Beschreibung aufgeführt. Nach dem Klicken auf den Namen ist die Eingabe der Login-Daten nötig und dann gelangt man zum ACP.

Die Optionen 1 und 3 schließen einander aus. Die Option 2 kann zusätzlich zu den Optionen 1 oder 3 gewählt werden.

# Funktionen freigeben und konfigurieren

Folgende Funktionen stehen für den Nur-Lese-Zugriff in dem jeweiligen ACP zur Verfügung:

* Interaktive Ansicht aller Daten eines ACP-Index
* Liste aller Units des ACP

Der ACP-Manager legt fest, welche weiteren Funktionen für den Nur-Lese-Zugriff in dem jeweiligen ACP zur Verfügung stehen und kann diese Funktionen teilweise konfigurieren:

* Download des ACP-Index
* Download von Units (Zip-Datei)
* Download anderer ACP-Dateien
* Ansicht/Abspielen von Units (über Verona-Player); hier kann festgelegt werden,
  - ob zusätzlich die Anzeige von Metadaten, RichText-Inhalten und Kodierschema möglich ist
  - ob die Units aus der obigen Liste aller Units des ACP aufgerufen werden können
  - ob aus Testcenter-Booklets des ACP Aufgabenfolgen gebildet werden sollen, die dann die Anzeige mehrerer Units in Folge ermöglicht
  - ob Kommentare zu Units, Items und/oder Aufgabenfolgen gegeben werden können
* Erzeugen und Anzeige einer Liste aus allen Items des ACP; hier kann festgelegt werden,
  - welche Unit- und Item-Metadaten in die Liste kopiert werden sollen,
  - ob ein Item bei Klick auf den Listeneintrag angezeigt werden soll
  - ob bei der Anzeige eines Items zusätzlich die Anzeige von Metadaten, RichText-Inhalten und Kodierschema möglich ist
  - ob die Itemliste gefiltert und sortiert werden kann
  - ob für Items in der Liste Markierungen vergeben werden können (Tags); welche Tags sind möglich?
  - ob die gewählte Sortierung, der gewählte Filter und die vergebenen Markierungen nutzerspezifisch gespeichert werden sollen (nur möglich bei Zugriffsbeschränkung)
