---
lang: de
title: ContentPool
---

Der IQB-ContentPool ist eine Webanwendung. Es handelt sich also um Software, die auf einem Server installiert werden muss. Man kann nach der Anmeldung die Daten verwalten und Zugriffe steuern.

::: {.callout-note}

Die Veröffentlichung eines Prototyps für den IQB-ContentPool ist Mitte 2026 vorgesehen.

:::

Der ContentPool speichert Daten, die für die Durchführung und Auswertung einer spezifischen Erhebung (Lernstandserhebung oder Befragung) erforderlich sind. Diese inhaltlich zusammengehörenden Daten werden nachfolgend als "Assessment Content Package - ACP" bezeichnet.

# Daten des ACP

## ACP-Index

Für jedes ACP muss genau je eine Datenstruktur "ACP-Index" verfügbar sein, die die zentralen Informationen über das ACP enthält. Viele Daten sind in anderen Dateien gespeichert, aber erst über die Referenzierung durch den ACP-Index sind sie nutzbar. Beim Anlegen des ACP wird ein ACP-Index automatisch mit Hilfe der Standard-Einstellungen des ContentPools angelegt.

Der ACP-Index kann als eine JSON-Datei exportiert (download) und importiert (upload) werden. Die Datenstruktur ist [hier](https://iqb-specifications.github.io/acp-index/) spezifiziert. Ein Upload eines ACP-Index überschreibt einen vorhandenen ACP-Index. Sollte der neue ACP-Index erforderliche Daten (required) nicht enthalten, werden sie automatisch durch Standard-Einstellungen des ContentPools ergänzt.

Der ContentPool unterstützt das Ändern von Daten des ACP-Index durch verschiedene Formulare, automatische Analysen und Validierungen.

## Dateien

Ein großer Teil der in einem ACP gespeicherten Daten besteht aus Dateien. Diese sind dazu bestimmt, außerhalb des ContentPools in Erhebungen eingesetzt zu werden, beispielsweise durch die Webanwendung IQB-Testcenter. Jede Datei muss im ACP-Index aufgeführt sein und es muss im ACP-Index deklariert werden, welche spezifische Funktion die Datei hat.

Da die Dateien komplexe Erhebungen steuern, müssen sie Daten-Spezifikationen folgen (syntaktische Validität) und innerhalb des ACP konsistent sein  (semantische Validität). Wenn beispielsweise ein Booklet eine Unit über ihre ID referenziert, muss diese Unit im ACP auch vorhanden sein. Eine wichtige Aufgabe des ContentPool ist es, die Dateien zu validieren. Beide Anforderungen - syntaktische und semantische Validierung - führen dazu, dass der ContentPool beim Hochladen von Dateien eine Analyse durchführen und auf mögliche Probleme hinweisen muss.

Die Dateien werden durch den ContentPool nicht verändert. Wenn bei der Validierung Probleme festgestellt werden, müssen die Dateien außerhalb des ContentPool verändert und erneut in den ContentPool hochgeladen werden.

## Versionierung

Zu einem beliebigen Zeitpunkt kann der Bearbeitungsstand eines ACP (ACP-Index plus Dateien) mit einem Zeitstempel markiert werden und wird dann als Snapshot gespeichert. Alle folgenden Änderungen können dann über eine Rückkehr zu diesem Snapshot rückgängig gemacht werden. Ein Snapshot ist mit einem Commit in einem Versionsverwaltungssystem vergleichbar. Zu jedem Snapshot kann es einen Text geben, der die Änderungen zum vorherigen Snapshot aufführt und erläutert. Der ContentPool unterstützt die Auflistung der Änderungen zum vorherigen Snapshot durch Vergleiche von Dateien.

# Nutzungsszenarien eines ACP

## Bereitstellung für die Öffentlichkeit

Um bestimmte Technologien oder Erhebungsverfahren besser bekannt zu machen, sind auf vorhandenen öffentlichen Dokumentationen Links platziert. Diese führen in einen ContentPool und ermöglichen jeder unbekannten, nicht autorisierten Person, die für die Nutzung erforderlichen Dateien anzuschauen und herunterzuladen. Es sind einzelne Aufgaben oder Aufgabenfolgen verfügbar.

## Download durch autorisierte Personen

Der ContentPool kann der Übergabepunkt für Leistungen sein: Eine Firma oder Einrichtung erstellt im Auftrag Testinhalte und übergibt an den Auftraggeber die Leistung über einen ContentPool. Der Auftraggeber kann dann nach Autorisierung die für die Nutzung erforderlichen Dateien anschauen und herunterladen.

Dieses Szenario wird beispielsweise genutzt, wenn das IQB die Testinhalte für VERA an die Länder ausliefert.

## Zwischenspeicher/Backup

Es ist auch möglich, dass die Testinhalte (insbes. die Aufgaben) im ContentPool einen vorläufigen Bearbeitungsstand haben. Dann dient der ContentPool als Backup-Lösung oder Zwischenspeicher. Zu einem späteren Zeitpunkt kann eine autorisierte Person die Aufgaben in ein IQB-Studio importieren und bearbeiten.

## Ansicht und Kommentierung von Aufgaben

In diesem Szenario schauen sich autorisierte Personen eine durch den Betreiber des ContentPools vorbereitete Folge von Aufgaben an. Für jede Aufgabe können auch Metadaten und Kodierschema angeschaut werden. Es ist möglich, diese Aufgaben und die darin enthaltenen Items zu kommentieren. Die Kommentare können dann von diesen Personen heruntergeladen werden (z. B. Xlsx). Außerdem kann der Betreiber die Kommentare aller Personen zusammen herunterladen.

Dieses Szenario wird genutzt, wenn Länder die VERA-Aufgaben in einer Vorversion beurteilen sollen, bevor diese Aufgaben in einer Pilotierung eingesetzt werden (sog. Länderreview).

## Ansicht von Items

Items sind innerhalb von Aufgaben definiert. In diesem Szenario schauen sich autorisierte Personen eine durch den Betreiber des ContentPools vorbereitete Folge von Items an. Dazu wird eine Liste aller Items mit allen Metadaten erzeugt. Diese Liste kann sortiert und gefiltert werden. Von dieser Liste kann man direkt in eine Aufgabenansicht wechseln. Außerdem werden Metadaten und Kodierschema der Aufgabe angezeigt.

Dieses Szenario wird genutzt, um die Identifikation von Items zu unterstützen, die einen Wechsel von einer Kompetenzstufe zu einer anderen markieren. Diese Item-Identifikation erfolgt im Rahmen von Expertentreffen für die Erarbeitung eines Kompetenzstufenmodells (sog. Ordered-Item-Booklet für Standard Setting).

# Funktionen der allgemeinen Anwendungsverwaltung

Nach der Installation des ContentPools ist mindestens ein Account mit der Rolle "**Application-Admin**" angelegt. Diese Rolle hat das Recht, folgende Funktionen auszuführen:

* Grundeinstellungen für den ContentPool festlegen
  - Farbgebung/Theme, Sprache, Logo
  - Texte für Startseite, Impressum, Datenschutz und Erklärung für Barrierefreiheit
  - Standard-Einstellungen für ACP-Index
* Nutzer anlegen und löschen
* Assessment Content Package anlegen, löschen, umbenennen
* Nutzern die Rolle "ACP-Manager" zuweisen für ACP
* Nutzern die Rolle "Application-Admin" zuweisen

# Funktionen der ACP-Verwaltung

Ein Assessment Content Package (ACP) muss vorher über einen Nutzer mit der Rolle "Application-Admin" angelegt werden. Außerdem muss mindestens einem Nutzer die Rolle "**ACP-Manager**" zugewiesen sein. Nach dem Login erhält ein ACP-Manager eine Liste aller ACP, auf die er Zugriff hat, und kann in ein ACP wechseln. Die Rolle ACP-Manager hat das Recht, für das ACP folgende Funktionen auszuführen:

## Allgemeines Datenmanagement

* Ansicht, Upload, Download und Ändern von Daten des ACP-Index
* Upload und Download von ACP-Dateien
* Snapshot erzeugen
* Snapshot wiederherstellen
* Download und Löschen ggf. der über den Nur-Lese-Zugriff vergebenen Kommentare

## Nur-Lese-Zugriff auf das ACP erteilen

Der ACP-Manager kann einen Nur-Lese-Zugriff auf das ACP erteilen. Hierfür gibt es drei Modelle:

1. **Keine Beschränkung (Public)**: Bei diesem Modell hat jede nicht autorisierte Person Zugriff. Es gibt keine zeitliche Begrenzung. Der ACP wird auf der Startseite der Webanwendung ContentPool mit dem Namen und einer Beschreibung aufgeführt, so dass Interessierte zu den Daten des ACP finden.
2. **Nutzer des ContentPool**: Ein ACP-Manager kann einem Nutzer, der vorher durch einen Application-Admin angelegt wurde, für das ACP die Rolle Nur-Lese-Zugriff geben. Nach dem Login erhält der Nutzer dann eine Liste aller ACP, auf die er Zugriff hat, und kann in diese ACP wechseln.
3. **Benutzername und Kennwort**: Ein ACP-Manager kann eine Liste erstellen oder hochladen, in der pro Zeile ein Benutzername und ein Kennwort festgelegt ist. Diese Daten autorisieren den Nur-Lese-Zugriff für das ACP. Der ACP-Manager muss den Zugriff über diese Liste zeitlich begrenzen. Es ist ein Zeitraum von maximal 3 Monaten zulässig. Ein ACP, das über diesen Weg einen Zugriff erlaubt, wird auf der Startseite der Webanwendung ContentPool mit dem Namen und einer Beschreibung aufgeführt. Nach dem Klicken auf den Namen ist die Eingabe der Login-Daten nötig und dann gelangt man zum ACP.

Die Optionen 1 und 3 schließen einander aus. Die Option 2 kann zusätzlich zu den Optionen 1 oder 3 gewählt werden.

## Funktionen freigeben und konfigurieren

Folgende Funktionen stehen für den Nur-Lese-Zugriff in dem jeweiligen ACP zur Verfügung:

* Interaktive Ansicht aller Daten eines ACP-Index
* Liste aller Units des ACP

Der ACP-Manager legt fest, welche weiteren Funktionen für den Nur-Lese-Zugriff in dem jeweiligen ACP zur Verfügung stehen und kann diese Funktionen teilweise konfigurieren:

* Download des ACP-Index
* Download von Units (Zip-Datei)
* Download anderer ACP-Dateien
* Ansicht/Abspielen von Units (über Verona-Player); hier kann festgelegt werden,
  - ob zusätzlich die Anzeige von Metadaten, RichText-Inhalten und Kodierschema möglich ist
  - ob die Units aus der obigen Liste aller Units des ACP aufgerufen werden können
  - ob aus Testcenter-Booklets des ACP Aufgabenfolgen gebildet werden sollen, die dann die Anzeige mehrerer Units in Folge ermöglicht
  - ob Kommentare zu Units, Items und/oder Aufgabenfolgen gegeben werden können
* Erzeugen und Anzeige einer Liste aus allen Items des ACP; hier kann festgelegt werden,
  - welche Unit- und Item-Metadaten in die Liste kopiert werden sollen,
  - ob ein Item bei Klick auf den Listeneintrag angezeigt werden soll
  - ob bei der Anzeige eines Items zusätzlich die Anzeige von Metadaten, RichText-Inhalten und Kodierschema möglich ist
  - ob die Itemliste gefiltert und sortiert werden kann
  - ob für Items in der Liste Markierungen vergeben werden können (Tags); welche Tags sind möglich?
  - ob die gewählte Sortierung, der gewählte Filter und die vergebenen Markierungen nutzerspezifisch gespeichert werden sollen (nur möglich bei Zugriffsbeschränkung)

