project:
  type: website

website:
  back-to-top-navigation: true
  site-url: https://iqb-berlin.github.io/rising-stars
  favicon: assets/favicon.ico
  repo-url: https://github.com/iqb-berlin/rising-stars
  title: StarS
  page-navigation: true
  navbar:
    pinned: true
    search: true
    logo: assets/iqb-logo-grey.png
    right:
      - icon: github
        href: https://github.com/iqb-berlin/rising-stars
  page-footer:
    border: true
    background: light
    right:
      - text: "IQB 2025"
        href: https://www.iqb.hu-berlin.de
    left:
      - href: index.qmd
        text: "{{< fa house >}}"
  sidebar: 
    style: "docked"
    search: true
    lang: de
    contents:
      - text: Überblick
        href: intro.qmd
      - section: Survey Content
        href: survey-content/index.qmd
        contents:
        - text: Kopfdaten
          href: survey-content/header.qmd
        - text: Abschnitte
          href: survey-content/parts.qmd
        - text: Instrumente
          href: survey-content/instruments.qmd
        - text: Skalen
          href: survey-content/scales.qmd

      - text: Coding-Service
        href: coding-service/index.qmd
      
format:
  html:
    theme: yeti
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    css: styles.css
    toc: true
