project:
  type: website
  resources:
    - player/assets/*.zip

website:
  back-to-top-navigation: true
  site-url: https://iqb-berlin.github.io/rising-stars
  favicon: assets/favicon.ico
  repo-url: https://github.com/iqb-berlin/rising-stars
  title: StarS Werkstatt
  page-navigation: true
  navbar:
    pinned: true
    search: true
    logo: assets/iqb-logo-grey.png
    right:
      - icon: github
        href: https://github.com/iqb-berlin/rising-stars
  page-footer:
    border: true
    background: light
    right:
      - text: "IQB 2025"
        href: https://www.iqb.hu-berlin.de
    left:
      - href: index.qmd
        text: "{{< fa house >}}"
  sidebar: 
    style: "docked"
    search: true
    lang: de
    contents:
      - text: Überblick
        href: intro.qmd
      - text: StarS-Player
        href: player/index.qmd
      - section: Content Package
        href: content-package/index.qmd
        contents:
          - text: Allgemeine Angaben
            href: content-package/header.qmd
          - text: Abschnitte
            href: content-package/parts.qmd
          - text: Instrumente
            href: content-package/instruments.qmd
          - text: Fähigkeitswerte
            href: content-package/scales.qmd

      - section: ResponseAnalyser
        href: response-analyser/index.qmd
        contents:
        - href: response-analyser/stars.qmd
          text: Szenario StarS
        - href: response-analyser/vera.qmd
          text: Szenario VERA

      - feedback.qmd

format:
  html:
    theme: yeti
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    css: styles.css
    toc: true
