project:
  type: website

website:
  back-to-top-navigation: true
  site-url: https://iqb-berlin.github.io/rising-stars
  favicon: assets/favicon.ico
  repo-url: https://github.com/iqb-berlin/rising-stars
  title: StarS
  page-navigation: true
  navbar:
    pinned: true
    search: true
    logo: assets/iqb-logo-grey.png
  page-footer:
    border: true
    background: light
    right:
      - text: "IQB 2025"
        href: https://www.iqb.hu-berlin.de
    left:
      - href: index.qmd
        text: "{{< fa house >}}"
  sidebar: 
    style: "docked"
    search: true
    lang: de
    contents:
      - section: Überblick
        href: survey/index.qmd
        contents:
          - text: Testinhalte
            href: survey/content.qmd
          - text: Testpersonen
            href: survey/testtakers.qmd
          - text: Testergebnisse
            href: survey/test-output.qmd
          - text: Datenanalyse
            href: survey/analysis.qmd
          - text: Ergebnisrückmeldung
            href: survey/feedback.qmd
      - text: Spezifikationen
        href: specs/index.qmd
      
format:
  html:
    theme: yeti
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    toc: true
