---
lang: de
title: Konzepte
---

# Art der Studien und Verfahren

## Allgemein

* Zuordnung der Items
  + Markierung über Metadaten (Item oder Unit)
  + explizite Liste (Item oder Unit)
* Erhebungsverfahren https://w3id.org/iqb/v85/v2/ 
  + [CAWI](https://w3id.org/iqb/v85/v2/13) (Computerunterstütztes Web-Interview)
  + [Laborbeobachtung teilnehmend](https://w3id.org/iqb/v85/v2/22)
  + [Computerbasierter Test](https://w3id.org/iqb/v85/v2/28)

## Befragung

* Ziele
  + Klassifizierung der Befragten (Beruf, Region, Alterstufe, Schulart…)
  + Evaluation
  + Feedback an Survey Authority
  + Erhebung Testteilnahme-Motivation für Wichtung der Beantwortung
* Kodierung
  + automatische Kodierung
  + nicht alles wird kodiert (freie Kommentare)
* Auswertung
  + Achtung: Evtl. Transformation von Erhebungswert zu Personenmerkmal
  + Erhebungswerte können zu Skalen aggregiert werden ([Konstrukte](https://w3id.org/iqb/v87/cq/); wie Skalenbildung?)
* Rückmeldedaten
  + Häufigkeiten
  + ordinale Skalen (Abstände nicht interpretierbar)

## Beobachtung oder Leistungstest

* Beobachtung: Erhebungseinheit wird beobachtet durch „Interviewer“, d. h. die Erhebungseinheit führt den Leistungstest nicht selbst durch
* Ziel
  + Feststellung relatives Leistungsniveau
  + isoliert bezogen auf eine (Sub-)Domäne (Lesen, Zuhören, Mathematik…)
* Kodierung
  + automatisch
  + manuell zentral
  + manuell dezentral durch Lehrkräfte
* Auswertung
  + Summe der Item-Scores pro Testheft und (Sub-)Domäne
  + Schätzung Personenfähigkeit über IRT pro (Sub-)Domäne; Abbildung der Schätzwerte auf einer veröffentlichten normierten Metrik
* Rückmeldedaten
  + Vergleich mit ähnlicher Population, mit Werten des Vorjahres derselben Person oder mit Norm
  + Score-Summe: % von Maximalpunktzahl, % von Norm; Eingruppierung in Leistungsbereiche (z. B. Quartile)
  + IRT: Numerischer Wert auf Norm-Skale, Eingruppierung in Stufenmodell
  + individuelle Rückmeldung zeigt Score pro Item an
  + Gruppenrückmeldung kann Lösungshäufigkeit der Gruppe den Lösungshäufigkeiten aus der Normierung/Pilotierung gegenüberstellen

