---
lang: de
title: Überblick
description: Begriffe und allgemeine Datenstrukturen
---

Im Englischen steht "Survey" für Befragungen und Leistungstests gleichermaßen. Das passt für den hier besprochenen Zusammenhang sehr gut. Im Deutschen gibt es keinen Begriff, der beides abdeckt - eher noch "Studie" als eine Forschungsunternehmung. Allerdings sind die hier beschriebenen Datenstrukturen überwiegend außerhalb konkreter Forschungsprojekte angesiedelt: Feststellung des Leistungsniveaus und Befragungen im Bildungswesen.

# Ziele

Am Anfang einer Studie steht stets das Ziel: Über eine bestimmte *Testpopulation* sollen *nützliche Erkenntnisse* gesammelt und bestimmten Zielpersonen *präsentiert* werden.

## Testpopulation

* Im Bildungskontext sind dies vor allem **Schüler\*innen** bestimmter Alters- bzw. Klassenstufen. 
* Weiterhin sind oft die **Lehrkräfte** Gegenstand der Erhebung. Erkenntnisse über Einstellungen, Methoden und Arbeitsumstände können wichtige Anregungen liefern.
* In einigen Studien werden auch **Eltern** befragt, um häusliche Entwicklungs- bzw. Lernumgebungen zu erfassen und in die Auswertung einfließen zu lassen.
* Schulleitung und Bildungsadministration können ebenfalls einbezogen werden.

Aus Sicht der Datenmodellierung sind folgende Punkte zu beachten:

* Die Testpopulation ist die Erhebungseinheit. Sie ist entweder direkt aktiv im Erhebungsprozess oder ihre Kompetenzen/Fähigkeiten werden von anderen über Beobachtungen oder Interviews erfasst. Im zweiten Fall sind auch die Einflüsse der Beobachter/Interviewer einzubeziehen.
* Personenmerkmale sind von herausragender Bedeutung für die Datenauswertung. Darüber werden Hypothesen geprüft und Handlungswissen abgeleitet. Beispiele:
  + Geschlecht
  + Sozioökonomischer Status
  + geografisch/administrative Zuordnung (Land, Bezirk, Gemeinde usw.)
  + Art/Typ des Schulträgers
  + Schulform usw.
* Personenmerkmale werden oft extern zugeführt, auch indirekt. Beispielsweise kann für eine Schule ein sozioökonomischer Index verfügbar sein, der dann auf alle Schüler\*innen der Schule übertragen wird.

## Nützliche Erkenntnisse

Die Erhebungen im Bildungssektor sind darauf ausgerichtet, allgemein zur Verbesserung der Tätigkeit der Beteiligten und der Rahmenbedingungen beizutragen. Die Quelle dafür ist die Ermittlung eines Leistungsstandes und der anschließende Vergleich: mit ähnlicher Population (Nachbarschule, innerhalb Klasse, anderes Land), mit Werten des Vorjahres derselben Person oder mit einer Norm (z. B. Bildungsstandards). Zusammen mit Personenmerkmalen und in Auseinandersetzung mit dem Erhebungsverfahren können Beziehungen konstruiert und damit Einflussfaktoren identifiziert werden.

## Präsentation

Um eine Wirksamkeit des Verfahrens zu erreichen, muss die Verwertung der Erkenntnisse bereits zu einem frühen Stadium der Planung berücksichtigt werden. Die theoretische Nützlichkeit der Erkenntnisse reicht nicht aus, sondern die Präsentation gegenüber einer Zielgruppe (Lehrkräfte, Bildungsadministration) muss zu praktisch umsetzbaren Fortschritten führen. Daher (a) ist die Gestaltung der Rückmeldung ein wesentlicher Erfolgsfaktor der Erhebung und (b) können passende Materialien oder Links zu Beginn der Erhebung mit entwickelt und entsprechend über Metadaten nutzbar gemacht werdne.

# Verfahren

Die folgende Darstellung bildet die Grundlage der folgenden Modellierungen. Jedes 
```{mermaid}
stateDiagram-v2
    classDef test fill:#6ff,stroke:black
    classDef others fill:#cff,stroke:black
    td: Testtakers definieren
    class td others
    sc: Survey Content erstellen
    class sc others
    tr: Test durchführen
    class tr test
    cr: Antworten kodieren
    class cr others
    ra: Daten analysieren
    class ra others
    fb1: Feedback an Individuen+Testgruppe
    class fb1 others
    fb2: Aggregiertes Feedback an Adminstration
    class fb2 others

    td --> tr
    sc --> tr
    tr --> cr
    cr --> ra
    ra --> fb1
    ra --> fb2
```

## Testtakers definieren



# Survey Content

Als Inhalte für eine Studie gelten alle Materialien und Daten, die unabhängig von konkreten Personen bereitgestellt werden. Das Modell geht hier von einem Content Provider aus: Eine Institution oder Firma stellt Inhalte bereit, mit denen Studien durchgeführt werden **KÖNNEN**. Ob und wann und wozu genau diese Studie dann durchgeführt wird, ist unbekannt.

Die Inhalte sind folgendermaßen gegliedert:

* 