---
lang: de
title: Survey Content Package
format:
    html:
        other-links:
            - text: Spezifikation SCP-Index
              href: https://iqb-specifications.github.io/scp-index
---

Unter einem Survey Content Package SCP verstehen wir alle Daten, die unabhängig von einer konkreten Durchführung bereitgestellt werden. Es handelt sich um

* **SCP-Index**: Eine Datei im Format JSON, die als Hauptverzeichnis dient und zahlreiche Datenstrukturen vereint (s. u.),
* **Content-Dateien**: Dateien in verschiedenen Formaten, die für die Durchführung über das Testcenter gedacht sind sowie Begleitmaterialien (Handreichungen, Auswertungshilfen usw.).

Für die Vorbereitung, Durchführung und Auswertung muss die durchführende Institution (Land, Dienstleister) weitere Informationen bereitstellen:

* Listen der Testpersonen,
* ggf. Leistungsdaten der Testpersonen aus vorangegangenen Testungen zum Vergleich
* ggf. Leistungsdaten auf Landes- oder Regionalebene zum Vergleich

Folgende Informationen enthält der SCP-Index:

* Kerndaten: Allgemeine Angaben wie ID, Name und Version für das SCP. Mit diesen Daten kann man aus einer Liste diverser Studien die passende auswählen. Die IQB-Webanwendung ContentPool wird diese Daten für die SCP-Verwaltung benötigen.
* Module und Testhefte, jeweils mit Metadaten und Zuordnungen zu Teilen der Testung
* Testmaterial für das Testcenter: Verweise auf Dateien und Zuordnung zu bestimmten Teilen der Testung
* Itemlisten und Skalenbuch: Vorschriften dafür, wie die Antworten zu Fähigkeitswerten transformiert werden
* Orientierungswerte aus Pilotierungen oder Normierungen für die Rückmeldung

**Spezifikationen**

* [Spezifikation für den Index](https://iqb-specifications.github.io/scp-index)
* [Komplettes Beispiel für den Index](https://github.com/iqb-specifications/scp-index/blob/main/test/index_1.json)
* [Metadaten-Profile für SCP](https://iqb-vocabs.github.io/p44/)
